### PR TITLE
Fix pbli157li90

### LINKED ISSUE #32: Fix approach for Pb157Li90 in pure materials
This definition uses a precomputed Li enrichment as part of the full element vector.  Instead make a Li Material and use that in the definition using eutectic atom fractions

### PR DESCRIPTION
**Pull request by Edgar-21**
closes #32 

I removed molecular mass from the material definition, since that gets calculated automatically when mixing by atom fraction. It is slightly different than the value entered manually before, but also now shows up in the JSON output. @bohmt do these seem like ok changes? Not sure what molecular mass was being used for before, or if it was just a fix for defining by mass fractions?

### CODE REVIEW

**Comment by FusionSandwich** [comment]
From when I tested it, it seems molecular mass was only needed for it as a mass fraction.

**Review by gonuke — APPROVED** [review]
This looks good to me.  I think we might actually want to drop the `molecular_mass` setting from our `make_material` method anyway and make users explicitly set it if they have some reason to.

**Comment by gonuke** [comment]
I'll wait for @bohmt to chime in before merging

**Comment by bohmt** [comment]
sorry for the delay in looking at this PR, I think it looks good so I'll merge it.

**Pull request merged**
